declare enum SpellSchoolMask
{
    SPELL_SCHOOL_MASK_NONE    = 0,
    SPELL_SCHOOL_MASK_NORMAL  = 1,
    SPELL_SCHOOL_MASK_HOLY    = 2,
    SPELL_SCHOOL_MASK_FIRE    = 4,
    SPELL_SCHOOL_MASK_NATURE  = 8,
    SPELL_SCHOOL_MASK_FROST   = 16,
    SPELL_SCHOOL_MASK_SHADOW  = 32,
    SPELL_SCHOOL_MASK_ARCANE  = 64,
}